name: main
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

env:
  GO_VERSION: 1.18

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build
        run: |
          go build ./...
      - name: test
        run: |
          go test -v
      - name: bench
        run: |
          go test -bench .

